### ISSUE TITLE
infinite “paste” loop

### ISSUE THREAD

**Issue by PauleBertt** [blockfirm/pine-app#7]
If i have anything in my clipboard ( even non btc stuff ) the app tries to paste it in an infinite loop
![image](https://user-images.githubusercontent.com/4346221/103748236-135ec000-5004-11eb-9b5d-72a84da3e413.jpeg)

**Comment by timothyej** [comment]
Hi,

This is a bug that is caused by the app checking every second if there is any bitcoin address in clipboard (iOS 14 only).

This will soon be fixed, thanks for reporting.
